"""Flask web backend for PsychLit Daily — wraps Python scripts as REST API + serves UI."""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime
from pathlib import Path
from threading import Lock

from flask import Flask, jsonify, request, send_from_directory

# Ensure scripts module is importable
SCRIPT_DIR = Path(__file__).resolve().parent.parent / "scripts"
DATA_DIR = Path(__file__).resolve().parent.parent / "data"
sys.path.insert(0, str(SCRIPT_DIR))

import search_literature as sl
import format_digest as fd

app = Flask(__name__, static_folder=".", static_url_path="")
_lock = Lock()
PUBLISHED_FILE = DATA_DIR / "published.html"

# ── helpers ──────────────────────────────────────────────────────────

def _load_config() -> dict:
    cfg_path = SCRIPT_DIR / "config.yaml"
    if not cfg_path.exists():
        cfg = {}
    else:
        import yaml
        with cfg_path.open(encoding="utf-8") as f:
            cfg = yaml.safe_load(f) or {}
    return cfg


def _load_history() -> list[dict]:
    path = DATA_DIR / "sent_history.json"
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8"))


def _save_history(history: list[dict]) -> None:
    path = DATA_DIR / "sent_history.json"
    path.write_text(json.dumps(history, ensure_ascii=False, indent=2), encoding="utf-8")


def _load_manual() -> list[dict]:
    path = DATA_DIR / "manual_papers.json"
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8"))


def _save_manual(papers: list[dict]) -> None:
    path = DATA_DIR / "manual_papers.json"
    path.write_text(json.dumps(papers, ensure_ascii=False, indent=2), encoding="utf-8")


_PUBLIC_PAGE_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{title}</title>
<style>
  body {{ font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; margin:0; padding:0; background:#f5f5f5; color:#333; }}
  .container {{ max-width:720px; margin:0 auto; padding:16px; }}
  .header {{ background:#1a5fb4; color:#fff; padding:20px; border-radius:8px; margin-bottom:20px; }}
  .header h1 {{ margin:0; font-size:22px; }}
  .header p {{ margin:8px 0 0; opacity:0.9; font-size:14px; }}
  .nav {{ text-align:right; margin-bottom:12px; }}
  .nav a {{ color:#1a5fb4; font-size:13px; text-decoration:none; }}
  .footer {{ text-align:center; font-size:12px; color:#999; padding:20px; }}
  .empty {{ text-align:center; padding:60px 20px; color:#888; }}
</style>
</head>
<body>
<div class="container">
  <div class="nav"><a href="/admin">Dashboard</a></div>
  <div class="header">
    <h1>Psychology Literature Daily</h1>
    <p>{subtitle}</p>
  </div>
  {content}
  <div class="footer">Auto-generated by Psychology Literature Daily &middot; Data: PubMed</div>
</div>
</body>
</html>"""


def _wrap_public_page(html_body: str, title: str, subtitle: str) -> str:
    return _PUBLIC_PAGE_TPL.format(title=title, subtitle=subtitle, content=html_body)


# ── Routes ───────────────────────────────────────────────────────────

@app.route("/")
def homepage():
    if PUBLISHED_FILE.exists():
        return PUBLISHED_FILE.read_text(encoding="utf-8")
    empty = '<div class="empty"><h2>No content yet</h2><p>Use the dashboard to publish the latest papers.</p><p><a href="/admin" style="color:#1a5fb4;">Go to Dashboard</a></p></div>'
    return _wrap_public_page(empty, "Psychology Literature Daily", "No papers published yet")


@app.route("/admin")
def admin():
    return send_from_directory(".", "index.html")


@app.route("/api/status")
def api_status():
    cfg = _load_config()
    history = _load_history()
    topics = cfg.get("topics", [])
    today = datetime.now().strftime("%Y-%m-%d")
    today_count = sum(1 for h in history if h.get("sent_at", "").startswith(today))
    return jsonify({
        "papers_today": today_count,
        "papers_week": len(history),
        "topics_count": len(topics),
        "scheduled": "8:00 AM daily",
        "last_send": history[-1]["sent_at"] if history else None,
        "topic_breakdown": {t.get("name", "?"): 0 for t in topics},
        "status": "ready",
    })


@app.route("/api/search", methods=["POST"])
def api_search():
    data = request.get_json(silent=True) or {}
    days_back = int(data.get("days_back", 1))
    max_papers = int(data.get("max_papers", 10))

    with _lock:
        cfg = _load_config()
        cfg.setdefault("search", {})["days_back"] = days_back
        cfg.setdefault("search", {})["max_papers"] = max_papers
        papers, stats = sl.search_all(cfg)
        manual = sl.load_manual_papers(str(DATA_DIR / "manual_papers.json"))
        if manual:
            papers = sl.sort_papers(papers + manual)[:max_papers]
        history = _load_history()
        keys = {h["key"] for h in history if "key" in h}
        papers, skipped = sl.filter_history(papers, keys)

    result = []
    for p in papers:
        result.append({
            "topic": p.topic,
            "title": p.title,
            "authors": p.authors,
            "journal": p.journal,
            "date": p.date,
            "abstract": (p.abstract or "")[:300],
            "doi": p.doi,
            "pmid": p.pmid,
            "url": p.url,
            "fulltext_url": p.fulltext_url,
            "is_oa": p.is_oa,
            "source": p.source,
        })

    return jsonify({
        "papers": result,
        "total_raw": stats.total_raw,
        "total_after_dedupe": stats.total_after_dedupe,
        "skipped_history": skipped,
        "topic_hits": stats.topic_hits,
    })


@app.route("/api/publish", methods=["POST"])
def api_publish():
    data = request.get_json(silent=True) or {}
    days_back = int(data.get("days_back", 1))
    max_papers = int(data.get("max_papers", 10))

    with _lock:
        cfg = _load_config()
        cfg.setdefault("search", {})["days_back"] = days_back
        cfg.setdefault("search", {})["max_papers"] = max_papers
        papers, stats = sl.search_all(cfg)
        manual = sl.load_manual_papers(str(DATA_DIR / "manual_papers.json"))
        if manual:
            papers = sl.sort_papers(papers + manual)[:max_papers]
        history = _load_history()
        keys = {h["key"] for h in history if "key" in h}
        papers, skipped = sl.filter_history(papers, keys)

        subject, combined = fd.format_digest_html(papers, stats, skipped, days_back, is_test=False)
        html_body, _ = fd.split_html_plain(combined)

        subtitle = f"Published {datetime.now().strftime('%Y-%m-%d %H:%M')} &middot; {len(papers)} papers"
        full_html = _wrap_public_page(html_body, subject, subtitle)
        PUBLISHED_FILE.write_text(full_html, encoding="utf-8")

        if papers:
            now_iso = datetime.now().isoformat()
            for p in papers:
                history.append({"key": p.dedupe_key(), "title": p.title, "sent_at": now_iso})
            _save_history(history)

    return jsonify({
        "success": True,
        "papers_count": len(papers),
        "skipped": skipped,
        "url": "/",
    })


@app.route("/api/history")
def api_history():
    history = _load_history()
    return jsonify(history)


@app.route("/api/config", methods=["GET", "POST"])
def api_config():
    if request.method == "POST":
        data = request.get_json(silent=True) or {}
        cfg_path = SCRIPT_DIR / "config.yaml"
        import yaml
        with cfg_path.open("r", encoding="utf-8") as f:
            cfg = yaml.safe_load(f) or {}
        if "smtp" in data:
            cfg["smtp"].update(data["smtp"])
        if "email" in data:
            cfg["email"].update(data["email"])
        if "search" in data:
            cfg["search"].update(data["search"])
        if "topics" in data:
            cfg["topics"] = data["topics"]
        with cfg_path.open("w", encoding="utf-8") as f:
            yaml.dump(cfg, f, allow_unicode=True, default_flow_style=False)
        return jsonify({"success": True})
    cfg = _load_config()
    return jsonify(cfg)


@app.route("/api/import", methods=["GET", "POST", "DELETE"])
def api_import():
    if request.method == "GET":
        return jsonify(_load_manual())
    if request.method == "POST":
        paper = request.get_json(silent=True) or {}
        if not paper.get("title"):
            return jsonify({"error": "Title is required"}), 400
        manual = _load_manual()
        manual.append(paper)
        _save_manual(manual)
        return jsonify({"success": True, "count": len(manual)})
    if request.method == "DELETE":
        body = request.get_json(silent=True) or {}
        idx = body.get("index")
        manual = _load_manual()
        if idx is not None and 0 <= idx < len(manual):
            manual.pop(idx)
        else:
            manual = []
        _save_manual(manual)
        return jsonify({"success": True, "count": len(manual)})


@app.route("/api/activity")
def api_activity():
    history = _load_history()
    recent = history[-20:] if len(history) > 20 else history
    return jsonify([{"key": h["key"], "title": h["title"], "sent_at": h["sent_at"]} for h in reversed(recent)])


# ── Run ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    debug = os.environ.get("FLASK_ENV") == "development"
    app.run(host="0.0.0.0", port=port, debug=debug)
